language: ruby
cache: bundler

rvm:
  - jruby
  - 2.1.1
  - 1.9

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - surajshirvankar@gmail.com
    on_failure: change
    on_success: never